### ISSUE TITLE
npm install exited with error code: 128 because of bignumber.js.git is inaccessible

### ISSUE THREAD

**Issue by michaelbaer** [blocklab/eventsexample#3]
Hi,

`npm install` failed with exit code 128.

```
2535 silly resolveWithNewModule xmlhttprequest@1.8.0 checking installable status
2536 silly fetchPackageMetaData error for bignumber.js@git+https://github.com/debris/bignumber.js.git#master exited with error code: 128
2537 verbose stack Error: exited with error code: 128
2537 verbose stack     at ChildProcess.onexit (/usr/local/lib/node_modules/npm/node_modules/mississippi/node_modules/end-of-stream/index.js:39:36)
2537 verbose stack     at emitTwo (events.js:125:13)
2537 verbose stack     at ChildProcess.emit (events.js:213:7)
2537 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:197:12)
2538 verbose cwd /usr/src/app
2539 verbose Linux 4.9.27-moby
2540 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
2541 verbose node v8.1.2
2542 verbose npm  v5.0.3
2543 error exited with error cod
```

I think it's the same issue like https://github.com/npm/npm/issues/17413

Michael

**Comment by michaelbaer** [comment]
Issue solved in dev dependency.
